# ======================
# Banco de Dados
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/clube_do_bolao?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# JWT
# ======================
jwt.secret=bolao2026_chave_secreta_muito_longa_para_ser_segura_minimo_256bits
jwt.expiration=86400000

# ======================
# Email (Gmail)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=sua_senha_de_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================
# App
# ======================
app.frontend.url=http://localhost:3000
spring.application.name=bolao-copa-2026